repositories:
  - name: "helm_charts"
#    url: 'git+https://github.com/harishbisht/generic-helm@charts?ref=v1.1.2'
    url: 'git+https://github.com/akash-codes93/helm_charts@charts?ref={{ env "HELM_CHARTS_REF" | default "v1.1.1" }}'

environments:
  local:
    values:
    - services:
      - webserver
      - job
      - cronjob


{{- $services := .Environment.Values.services }}
{{- $env := .Environment.Name }}


helmDefaults:
#  force: false
  timeout: {{env "HELMFILE_TIMEOUT"| default "600" }}
  verify: false
  wait: true
  atomic: true


releases:
{{- range $service:= $services }}
  - name: {{ $service | lower }}
    namespace: {{ requiredEnv "NAMESPACE" }}
    chart: helm_charts/{{ env "HELM_CHART" | default "base" }}
    version: {{ env "HELM_CHART_VERSION" | default "0.1.0" }}
    missingFileHandler: Info
    installed: true
    values:

#    - deploy/{{ $env }}/secrets.yaml.gotmpl
    - deploy/{{ $env }}/{{ $service }}.yaml.gotmpl

{{end}}