{{- $chartenvsecretsname := include "chart.envsecretsname" . }}
{{- $jobs := .Values.cronjobs }}
{{- $objectname := include "helm.fullname" . }}
{{- $pullsecretname := include "chart.pullSecretName" . }}
{{- $sa := .Values.serviceaccount }}
{{- $extSecret := include "chart.extSecret" . }}

{{- if $jobs }}{{- range $job := $jobs }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $objectname }}-{{ $job.name }}
spec:
  concurrencyPolicy: {{ $job.concurrencyPolicy }}
  {{- if $job.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ $job.startingDeadlineSeconds }}
  {{- end }}
  failedJobsHistoryLimit: {{ $job.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      {{- if $job.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ $job.activeDeadlineSeconds }}
      {{- end }}
      template:
        metadata:
          labels:
            app: {{ $objectname }}
            cron: {{ $job.name }}
          annotations:
            {{- if $job.templateAnnotations }}
            {{- toYaml $job.templateAnnotations | trimSuffix "\n" | nindent 12 }}
            {{- end }}
        spec:
          containers:
          - name: {{ $job.name }}
            image: {{ $job.image.repository }}:{{ $job.image.tag }}
            imagePullPolicy: {{ $job.image.imagePullPolicy | default "IfNotPresent" }}
            {{- if $job.command }}
            command: {{ $job.command }}
            {{- end }}
            {{- if $job.args }}
            args:
            {{- toYaml $job.args | trimSuffix "\n" | nindent 14 }}
            {{- end }}
            {{- if $job.env }}
            env:
            {{- range $key, $value := $job.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            envFrom:
              - secretRef:
                  name: {{ $extSecret }}
            {{- end }}
            {{- if $job.resources }}
            resources:
              {{- toYaml $job.resources | trimSuffix "\n" | nindent 14 }}
            {{- end }}
            {{- if $job.volumeMounts }}
            volumeMounts:
              {{- toYaml $job.volumeMounts | trimSuffix "\n" | nindent 14 }}
            {{- end }}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          {{- if $job.volumes }}
          volumes:
            {{- toYaml $job.volumes | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- if $job.nodeSelector }}
          nodeSelector:
            {{- toYaml $job.nodeSelector | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- if $job.affinity }}
          affinity:
            {{- toYaml $job.affinity | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- if $job.tolerations }}
          tolerations:
            {{- toYaml $job.tolerations | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          dnsPolicy: ClusterFirst
          restartPolicy: {{ $job.restartPolicy }}
          {{- if $job.securityContext }}
          securityContext:
            {{- toYaml $job.securityContext | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- if $job.terminationGracePeriodSeconds }}
          terminationGracePeriodSeconds: {{ $job.terminationGracePeriodSeconds }}
          {{- end }}
          imagePullSecrets:
            - name: {{ $pullsecretname }}
          {{- if $sa.enabled }}
          serviceAccount: {{ $sa.name }}
          serviceAccountName: {{ $sa.name }}
          {{- end }}
      {{- if $job.Parallelism }}
      parallelism: {{ $job.Parallelism }}
      {{- end }}
      {{- if $job.Completions }}
      completions: {{ $job.Completions }}
      {{- end }}
      {{- if $job.backoffLimit }}
      backoffLimit: {{ $job.backoffLimit }}
      {{- end }}
  schedule: {{ $job.schedule | quote }}
  successfulJobsHistoryLimit: {{ $job.successfulJobsHistoryLimit }}
  suspend: false
{{- end }}{{- end }}