
{{- if .Values.deployment.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  strategy:
    {{- toYaml .Values.deployment.strategy | trimSuffix "\n" | nindent 4 }}
  {{- if not .Values.hpa.autoscaling.enabled }}
  replicas: {{ .Values.hpa.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectors" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
{{/*        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }} */}}
        tag: "{{ .Values.app.image.tag }}"
        {{- if .Values.app.podAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.app.podAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
      labels:
        {{- include "chart.selectors" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port | default 8080 }}
              protocol: TCP
          {{- if .Values.app.command }}
          command:
            {{- toYaml .Values.app.command | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- if .Values.app.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.app.livenessProbe | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- if .Values.app.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.app.readinessProbe | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          env:
            {{- range $key, $value := .Values.app.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $secret := .Values.app.envSecrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "chart.envsecretsname" }}
                  key: {{ $key | quote }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "helm.fullname" . }}
      {{- if .Values.imageCredentials.registry }}
      imagePullSecrets:
        - name: {{ include "app.pullSecretName" . }}
      {{- end }}
      {{- if .Values.serviceaccount.enabled }}
      serviceAccountName: {{ .Values.serviceaccount.name }}
      {{- end }}
      {{- if and (not .Values.serviceaccount.enabled) .Values.deployment.serviceAccountName }}
      serviceAccountName: {{ .Values.deployment.serviceAccountName }}
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.deployment.nodeSelector | trimSuffix "\n" | nindent 8 }}
      affinity:
        {{- toYaml .Values.deployment.affinity | trimSuffix "\n" | nindent 8 }}
      tolerations:
        {{- toYaml .Values.deployment.tolerations | trimSuffix "\n" | nindent 8 }}
      securityContext:
        {{- toYaml .Values.deployment.securityContext | trimSuffix "\n" | nindent 8 }}

{{- end }}
