{{- $hpa := .Values.hpa }}

{{- if .Values.hpa.autoscaling.enabled -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "helm.fullname" . }}
  minReplicas: {{ .Values.hpa.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.hpa.autoscaling.maxReplicas }}
  metrics:
    {{- toYaml $hpa.metrics | trimSuffix "\n" | nindent 4 }}
  {{- if $hpa.behavior }}
  behavior:
    {{- toYaml $hpa.behavior | trimSuffix "\n" | nindent 4 }}
  {{- end }}
{{- end }}
