{{- $objectname := include "helm.fullname" . }}
{{- $chartlabels := include "chart.labels" . }}
{{- $jobs := .Values.jobs }}
{{- $pullsecretname := include "chart.pullSecretName" . }}
{{- $sa := .Values.serviceaccount }}
{{- $extSecret := include "chart.extSecret" . }}


{{- if $jobs }}{{- range $job := $jobs }}
{{- if $job.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $objectname }}-{{ $job.name }}
  labels:
    {{- $chartlabels | nindent 4 }}
  {{- if $job.annotations }}
  annotations:
  {{- toYaml $job.annotations | trimSuffix "\n" | nindent 4 }}
  {{- end }}
spec:
  {{- if $job.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ $job.ttlSecondsAfterFinished }}
  {{- end }}
  template:
    metadata:
      name: {{ $objectname }}-{{ $job.name }}
      labels:
        app: {{ $objectname }}
      {{- if $job.templateAnnotations }}
      annotations:
        {{- toYaml $job.templateAnnotations | trimSuffix "\n" | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: {{ $job.restartPolicy }}
      containers:
      - name: {{ $job.name }}
        image: {{ $job.image.repository }}:{{ $job.image.tag }}
        imagePullPolicy: {{ $job.image.imagePullPolicy | default "IfNotPresent" }}
        {{- if $job.command }}
        command: {{ $job.command }}
        {{- end }}
        {{- if $job.args }}
        args:
          {{- toYaml $job.args | trimSuffix "\n" | nindent 14 }}
        {{- end }}
        env:
        {{- range $key, $value := $job.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        envFrom:
          - secretRef:
              name: {{ $extSecret }}
        {{- if $job.resources }}
        resources:
          {{- toYaml $job.resources | trimSuffix "\n" | nindent 10 }}
        {{- end }}
        {{- if $job.volumeMounts }}
        volumeMounts:
          {{- toYaml . | trimSuffix "\n" | nindent 10 }}
        {{- end }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      {{- if $job.volumes }}
      volumes:
        {{- toYaml $job.volumes | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      {{- if $job.nodeSelector }}
      nodeSelector:
        {{- toYaml $job.nodeSelector | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      {{- if $job.affinity }}
      affinity:
        {{- toYaml $job.affinity | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      {{- if $job.tolerations }}
      tolerations:
        {{- toYaml $job.tolerations | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: {{ $job.restartPolicy }}
      {{- if $job.securityContext }}
      securityContext:
        {{- toYaml $job.securityContext | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      {{- if $job.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ $job.terminationGracePeriodSeconds }}
      {{- end }}
      imagePullSecrets:
        - name: {{ $pullsecretname }}
      {{- if $sa.enabled }}
      serviceAccount: {{ $sa.name }}
      serviceAccountName: {{ $sa.name }}
      {{- end }}
  {{- if $job.Parallelism }}
  parallelism: {{ $job.Parallelism }}
  {{- end }}
  {{- if $job.Completions }}
  completions: {{ $job.Completions }}
  {{- end }}
  {{- if $job.backoffLimit }}
  backoffLimit: {{ $job.backoffLimit }}
  {{- end }}
  {{- if $job.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ $job.activeDeadlineSeconds }}
  {{- end }}
{{- end }}{{- end }}{{- end }}
