{{- $service := .Values.service -}}

{{- if $service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ $service.type }}
  ports:
    {{- toYaml $service.ports | trimSuffix "\n" | nindent 4 }}
  selector:
    {{- include "chart.selectors" . | nindent 4 }}
    app.kubernetes.io/component: web
{{- end }}