
{{- $sa := .Values.serviceaccount }}

{{- if $sa.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa.name }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml $sa.annotations | trimSuffix "\n" | nindent 4 }}
{{- end }}
