# Generated by Django 4.0.4 on 2023-10-01 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lines',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'parcels',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('cost', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lines', models.ManyToManyField(to='long_mail_service.line')),
            ],
            options={
                'db_table': 'trains',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='long_mail_service.line')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='long_mail_service.train')),
            ],
            options={
                'db_table': 'trips',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='long_mail_service.parcel')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='long_mail_service.trip')),
            ],
            options={
                'db_table': 'bookings',
                'managed': True,
            },
        ),
    ]
