# Generated by Django 4.0.4 on 2023-10-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_mail_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cost',
            field=models.FloatField(),
        ),
    ]
