# Generated by Django 4.0.4 on 2023-10-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_mail_service', '0002_alter_booking_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='strategy',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
